{"data": "Traceback (most recent call last):\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\jiant-2.2.0-py3.8.egg\\jiant\\utils\\zlog.py\", line 39, in log_context\n    yield self\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\jiant-2.2.0-py3.8.egg\\jiant\\proj\\main\\runscript.py\", line 140, in run_loop\n    runner = setup_runner(\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\jiant-2.2.0-py3.8.egg\\jiant\\proj\\main\\runscript.py\", line 92, in setup_runner\n    jiant_model_setup.delegate_load_from_path(\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\jiant-2.2.0-py3.8.egg\\jiant\\proj\\main\\modeling\\model_setup.py\", line 90, in delegate_load_from_path\n    weights_dict = torch.load(weights_path)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\torch\\serialization.py\", line 579, in load\n    with _open_file_like(f, 'rb') as opened_file:\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\torch\\serialization.py\", line 230, in _open_file_like\n    return _open_file(name_or_buffer, mode)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\torch\\serialization.py\", line 211, in __init__\n    super(_open_file, self).__init__(open(name, mode))\nPermissionError: [Errno 13] Permission denied: './test_experiment/model'\n", "TIMESTAMP": 1622036249.4399579}
